### ISSUE TITLE
Cannot load ruby gem

### ISSUE THREAD

**Issue by ginjo** [wilsonzlin/minify-html#189]
The ruby command ```require 'minify_html'``` produces an error and fails to load the gem.

Here is documentation showing platform, OS, ruby & gem versions, the failing command and the resulting error:

```
jsv_app:/app$ uname -a
Linux jsv_app 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux

jsv_app:/app$ cat /etc/*releas*
3.17.4                   
NAME="Alpine Linux"      
ID=alpine
VERSION_ID=3.17.4
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

jsv_app:/app$ ruby --version
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux-musl]

jsv_app:/app$ gem --version
3.3.26

jsv_app:/app$ bundler --version
Bundler version 2.3.26

jsv_app:/app$ bundle list
Gems included by the bundle:
  * addressable (2.8.5)  
  * allora (0.1.10)      
  * amq-protocol (2.3.2) 
  * aws-eventstream (1.3.0)
  * aws-partitions (1.863.0)
  * aws-sdk-core (3.190.0)
  * aws-sdk-sns (1.60.0) 
  * aws-sigv4 (1.8.0)    
  * base64 (0.2.0)       
  * bigdecimal (3.1.4)   
  * bunny (2.22.0)
  * bunny_wrapper (0.1.0 5926c54)
  * concurrent-ruby (1.2.2)
  * connection_pool (2.4.1)
  * cookiejar (0.3.3)
  * domain_name (0.6.20231109)
  * dotenv (2.7.6)
  * dry-container (0.11.0)
  * dry-core (0.9.1)
  * dry-equalizer (0.3.0)
  * dry-inflector (0.3.0)
  * dry-initializer (3.1.1)
  * dry-logic (1.3.0)
  * dry-struct (1.5.2)
  * dry-types (1.6.1)
  * em-hiredis (0.3.1)
  * em-http-request (1.1.7)
  * em-socksify (0.3.2)
  * eventmachine (1.2.7)
  * execjs (2.9.1)
  * faraday (2.7.12)
  * faraday-net_http (3.0.2)
  * faye (1.4.0)
  * faye-redis (0.2.0)
  * faye-websocket (0.11.3)
  * ffi (1.16.3)
  * hashie (5.0.0)
  * hiredis (0.6.3)
  * http-accept (1.7.0)
  * http-cookie (1.0.5)
  * http_parser.rb (0.8.0)
  * i18n (1.14.1)
  * ice_nine (0.11.2)
  * jmespath (1.6.2)
  * json_rpc_object (0.0.1 665fa87)
  * jwt (2.7.1)
  * mime-types (3.5.1)
  * mime-types-data (3.2023.1205)
  * minify_html (0.15.0)
  * money (6.16.0)
  * multi_json (1.15.0)
  * multi_xml (0.6.0)
  * mustermann (3.0.0)
  * netrc (0.11.0)
  * nio4r (2.7.0)
  * oauth2 (2.0.9)
  * ox (2.14.17)
  * pg (1.4.6)
  * public_suffix (5.0.4)
  * puma (5.6.7)
  * rack (2.2.8)
  * rack-cache (1.13.0)
  * rack-protection (3.0.6)
  * rake (13.0.6)
  * rbtree (0.4.6)
  * redcarpet (3.6.0)
  * redis (4.5.1)
  * redis-rack (2.1.4)
  * redis-store (1.10.0)
  * rest-client (2.1.0)
  * rom (5.2.6)
  * rom-changeset (5.2.3)
  * rom-core (5.2.6)
  * rom-repository (5.2.2)
  * rom-sql (3.5.0)
  * ruby2_keywords (0.0.5)
  * sassc (2.4.0)
  * sequel (5.75.0)
  * set (1.0.3)
  * sinatra (3.0.6)
  * sinatra-contrib (3.0.6)
  * snaky_hash (2.0.1)
  * sorted_set (1.0.3)
  * sqlite3 (1.4.4)
  * stripe (10.2.0)
  * table_print (1.5.7)
  * tilt (2.0.11)
  * tilt-sassc (0.2.0)
  * transproc (1.1.1)
  * uglifier (4.2.0)
  * version_gem (1.1.3)
  * websocket-driver (0.7.6)
  * websocket-extensions (0.1.5)
  * zeitwerk (2.6.12)

jsv_app:/app$ bundle exec irb
irb(main):001:0> require 'minify_html'
/usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.rb:7:in `require_relative': cannot load such file -- /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.so (LoadError)
        from /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.rb:7:in `rescue in <top (required)>'
        from /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.rb:3:in `<top (required)>'
        from (irb):1:in `require'                                 
        from (irb):1:in `<main>'                                  
        from /usr/local/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'                      
        from /usr/local/bin/irb:25:in `<top (required)>'          
        from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
        from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	... 6 levels...
/usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.rb:5:in `require_relative': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/3.1/minify_html.so) - /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/3.1/minify_html.so (LoadError)
	from /usr/local/bundle/gems/minify_html-0.15.0-x86_64-linux/lib/minify_html.rb:5:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1:in `<main>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:25:in `load'
	from /usr/local/bin/irb:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	... 5 levels...
```

**Comment by ernestpasnik** [comment]
@ginjo try installing these packages and let me know if it solves the problem.
```
apk add libstdc++ gcompat
```

**Comment by ginjo** [comment]
Thanks for the tip, that solved the gem loading issue!

Unfortunately, the minify_html() method breaks my pages on all but the latest browsers. I'll experiment with the options and see if I can get it working.

**Comment by ginjo** [comment]
Just to follow up, the bugs were in *my* code, not in this gem. I cleaned up my code, adjusted the html-minify options, and all is working well now (except the v0.16 panic, but v0.15 works great).
