### ISSUE TITLE
Node package doesn't work with ESM modules

### ISSUE THREAD

**Issue by sondr3** [wilsonzlin/minify-html#65]
I just noticed this problem on a project I have where I have specificed `"type": "module"` in the `package.json`. With for example `@parcel/css` importing and running the native binary works fine, but for `@minify-html/js` I get the following error:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for /home/sondre/Code/web/node_modules/.pnpm/@minify-html+js@0.8.0/node_modules/@minify-html/js/index.node
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:22:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v17.3.0
```

Instead of being able to do `import * as minify from "@minify-html/js"` I have to do

```ts
import * as minify from "@minify-html/js"
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const mf = require("@minify-html/js") as typeof minify;
```

I have no idea really why this is a problem as both this and `@parcel/css` have `.node`-files in them, but this project gives me an error. The biggest difference that I can see is that this project builds the NodeJS package "manually" using `node-gyp` and such while `@parcel/css` uses `napi` to do the heavy lifting.

**Comment by sondr3** [comment]
It would be nice, the whole node ecosystem is ever so slowly moving towards ESM so it'd be nice to have it working without fuzzing about with imports :+1:

**Comment by vhscom** [comment]
The error produced by [Vite](https://vitejs.dev/) is a little different. Including below for reference:

```term
10:51:15 AM [vite] Error when evaluating SSR module //home/user/path/to/file:
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .node file format.
    at formatError (/home/user/path/to/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36769:46)
    at TransformContext.error (/home/user/path/tonode_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36765:19)
    at TransformContext.transform (/home/user/path/to/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73659:22)
    at async Object.transform (/home/user/path/to/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36985:30)
    at async doTransform (/home/user/path/to/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:52060:29)
```

Solution provided by OP works. Modified to add `type` after first import like:

```ts
import type * as minify from "@minify-html/js"
```

Then including the rest verbatim:

```ts
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const mf = require("@minify-html/js") as typeof minify;
```

SvelteKit 1.0.0-next.247
GNU/Linux 5.15.11-3

**Comment by vhscom** [comment]
Unfortunately the workaround seems to have its own warts. Here's what happens when running it inside a Node-alpine docker container:

```term
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/.pnpm/@minify-html+js@0.8.0/node_modules/@minify-html/js/index.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /app/src/hooks.ts:11:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instantiateModule (/app/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60105:9)
```

Just going to leave this here for posterity.

**Comment by endel** [comment]
When importing `@minify-html/js` from a child process (`child_process.spawn()`), and killing the main process, the child process will not terminate.

**Comment by wilsonzlin** [comment]
The latest version now has an `index.js` file that should allow for importing from ESM contexts. Let me know if it works on your end.

Note that the latest version is a minor version change, and there are changes to the Node.js library described in the changelog. Noticeably, esbuild has been replaced with [minify-js](https://github.com/wilsonzlin/minify-js), a JS minifier I wrote from scratch fully in Rust, so @endel there should no longer be any process/signals interference issues caused by the esbuild Go runtime similar to what you've described. Let me know if it works on your end.

Because of the aforementioned change, there are also now WASM versions available, if anyone is interested.

**Comment by SettingDust** [comment]
Seems wrong
```ts
import { minify } from '@minify-html/wasm';
         ^^^^^^
SyntaxError: Named export 'minify' not found. The requested module '@minify-html/wasm' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@minify-html/wasm';
const { minify } = pkg;
```

```
(node:3844) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

E:\javascript\article-extractor\node_modules\@minify-html\wasm\index.js:1
import * as wasm from "./index_bg.wasm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

And `No default export found in imported module "@minify-html/wasm"`
